@startuml SG_DataModule
!include IncludeFiles/Setting.pu
!define _VERSION_ 0.1.0
!define _FILE_CODE_ DataModule
!define _LAST_MODIFIED_ 2020-09-10
!include IncludeFiles/Layout.pu

object OtherClient{
    int myId
    PlayerData[] PlayerDatas
    NetworkData _NetworkData   
}

object NetworkData <<struct>>{
    int connect
    int sock
    sockaddr_in addr
}

object PlayerData <<struct>>{
    char[] name
    FloatCube cube
    float dir
    int rank
    bool goal
}

class BaseMapData{
    # int[][][] _TerrainData
    # vector<PlaceData> _ObjectDatas
    # int _MapW, _MapH, _MapD

    + const int(* GetTerrainData())
    + const vector<PlaceData> GetObjectData()
    + void PushBackObject(PlaceData *objectData)
}

package Server{
    object ServerGameDatas <<struct>>{
        + uint CurrentTime
    }

    object SMap{
        MapData MapData
    }

    object SSystem{
        - PlayerData[] PlayerDatas

        + const PlayerData* GetPlayerData(int id)
        + const PlayerData* GetAllPlayerDatas()
    }

    object SNetwork{
        NetworkData _NetworkData

        - SendData()
        + void GetSendCommand(char command)
        + void SetupServer()
        + void TerminateServer()
        + int ControlRequest()
    }

    class SMapData{

    }

    SMap <--> SSystem
    SNetwork <--> SSystem
    SMapData -- SMap
    BaseMapData <|-- SMapData
}

package Client{
    object CNetwork{
        NetworkData _NetworkData
    }

    object CMap{
        MapData MapData
    }

    object CSystem{
        int myId
        PlayerData[] PlayerDatas
    }

    object CGraphic{

    }

    object CInput{

    }

    object CInputData <<struct>>{
        bool Forward
        bool Right
        bool Left
        bool Jump
    }

    class CMapData{
        + void SetMapData(int mapW atc...)
    }

    CNetwork <--> CSystem
    CSystem <- CGraphic
    CMap <-- CSystem 
    CMap <-- CGraphic
    CInput -> CSystem
    CInputData . (CSystem, CInput)
    CMapData -- CMap
    BaseMapData <|-- CMapData
}

'== ネットワーク間のデータのやり取り =='
SNetwork <-> CNetwork
SNetwork <---> "n" OtherClient
'Network <.> "n" OtherClient : 相互参照
'(Network, OtherClient) . PlayerData
'== ネットワーク間のデータのやり取り =='

note as NF
マークなし : モジュール
<<struct>> : 構造体
C : クラス
end note

@enduml